using System.Collections.Generic;

namespace GameboyNetcore.Core
{
    public static class Licensees
    {
        public static Dictionary<int, string> New { get; set; } = new Dictionary<int, string>
        {
            {0x00, "none"},
            {0x13, "Electronic Arts"},
            {0x20, "kss"},
            {0x25, "san-x"},
            {0x30, "Viacom"},
            {0x33, "Ocean/Acclaim"},
            {0x37, "Taito"},
            {0x41, "Ubi Soft"},
            {0x46, "angel"},
            {0x50, "Absolute"},
            {0x53, "American sammy"},
            {0x56, "LJN"},
            {0x59, "Milton Bradley"},
            {0x64, "LucasArts"},
            {0x70, "Infogrames!"},
            {0x73, "sculptured"},
            {0x79, "Accolade"},
            {0x86, "tokuma shoten i*"},
            {0x92, "Video system"},
            {0x96, "Yonezawa/s'pal"},
            {0xA4, "Konami (Yu-Gi-Oh!)"},
            {0x01, "Nintendo R&D1"},
            {0x18, "Hudson Soft"},
            {0x22, "pow"},
            {0x28, "Kemco Japan"},
            {0x31, "Nintendo"},
            {0x34, "Konami"},
            {0x38, "Hudson"},
            {0x42, "Atlus"},
            {0x47, "Bullet-Proof"},
            {0x51, "Acclaim"},
            {0x54, "Konami"},
            {0x57, "Matchbox"},
            {0x60, "Titus"},
            {0x67, "Ocean"},
            {0x71, "Interplay"},
            {0x75, "sci"},
            {0x80, "misawa"},
            {0x87, "tsukuda ori*"},
            {0x93, "Ocean/Acclaim"},
            {0x97, "Kaneko"},
            {0x08, "Capcom"},
            {0x19, "b-ai"},
            {0x24, "PCM Complete"},
            {0x29, "seta"},
            {0x32, "Bandai"},
            {0x35, "Hector"},
            {0x39, "Banpresto"},
            {0x44, "Malibu"},
            {0x49, "irem"},
            {0x52, "Activision"},
            {0x55, "Hi tech entertainment"},
            {0x58, "Mattel"},
            {0x61, "Virgin"},
            {0x69, "Electronic Arts"},
            {0x72, "Broderbund"},
            {0x78, "THQ"},
            {0x83, "lozc"},
            {0x91, "Chunsoft"},
            {0x95, "Varie"},
            {0x99, "Pack in soft"}
        };

        public static Dictionary<int, string> Old { get; set; } = new Dictionary<int, string>
        {
            { 0x00, "none"},           
            { 0x09, "hot-b"},           
            { 0x0C, "elite systems"},           
            { 0x19, "itc entertainment"},           
            { 0x1F, "virgin"},           
            { 0x25, "san-x"},           
            { 0x30, "infogrames"},           
            { 0x33, "GBC - see above"},           
            { 0x38, "Capcom"},          
            { 0x3E, "gremlin"},              
            { 0x44, "Malibu"},           
            { 0x49, "irem"},           
            { 0x4F, "u.s. gold"},           
            { 0x52, "activision"},           
            { 0x55, "park place"},           
            { 0x59, "milton bradley"},           
            { 0x5C, "naxat soft"},          
            { 0x61, "virgin"},          
            { 0x6E, "elite systems"},          
            { 0x71, "Interplay"},          
            { 0x75, "the sales curve"},              
            { 0x7A, "triffix entertainment"},          
            { 0x80, "misawa entertainment"},          
            { 0x8B, "bullet-proof software"},          
            { 0x8F, "i'max"},           
            { 0x93, "tsuburava"},           
            { 0x97, "kaneko"},           
            { 0x9B, "Tecmo"},           
            { 0x9F, "nova"},           
            { 0xA4, "Konami"},           
            { 0xA9, "technos japan"},           
            { 0xAD, "toho"},           
            { 0xB1, "ascii or nexoft"},           
            { 0xB6, "HAL"},           
            { 0xBA, "*culture brain o"},           
            { 0xBF, "sammy"},           
            { 0xC3, "Squaresoft"},           
            { 0xC6, "tonkin house"},           
            { 0xCA, "ultra"},           
            { 0xCD, "meldac"},           
            { 0xD0, "Taito"},           
            { 0xD3, "sigma enterprises"},           
            { 0xD7, "copya systems"},           
            { 0xDB, "ljn"},           
            { 0xDF, "altron"},           
            { 0xE2, "uutaka"},           
            { 0xE7, "athena"},           
            { 0xEA, "king records"},           
            { 0xEE, "igs"},           
            { 0xFF, "ljn"},
            { 0x01, "nintendo"},
            { 0x0A, "jaleco"},
            { 0x13, "electronic arts"},
            { 0x1A, "yanoman"},
            { 0x20, "KSS"},
            { 0x28, "kotobuki systems"},
            { 0x31, "nintendo"},
            { 0x34, "konami"},
            { 0x39, "Banpresto"},
            { 0x41, "Ubisoft"},
            { 0x46, "angel"},
            { 0x4A, "virgin"},
            { 0x50, "absolute"},
            { 0x53, "american sammy"},
            { 0x56, "ljn"},
            { 0x5A, "mindscape"},
            { 0x5D, "tradewest"},
            { 0x67, "ocean"},
            { 0x6F, "electro brain"},
            { 0x72, "broderbund"},
            { 0x78, "t*hq"},
            { 0x7C, "microprose"},
            { 0x83, "lozc"},
            { 0x8C, "vic tokai"},
            { 0x91, "chun soft"},
            { 0x95, "varie"},
            { 0x99, "arc"},
            { 0x9C, "imagineer"},
            { 0xA1, "Hori electric"},
            { 0xA6, "kawada"},
            { 0xAA, "broderbund"},
            { 0xAF, "Namco"},
            { 0xB2, "Bandai"},
            { 0xB7, "SNK"},
            { 0xBB, "Sunsoft"},
            { 0xC0, "Taito"},
            { 0xC4, "tokuma shoten intermedia "},
            { 0xC8, "koei"},
            { 0xCB, "vap"},
            { 0xCE, "*pony canyon or"},
            { 0xD1, "sofel"},
            { 0xD4, "ask kodansha"},
            { 0xD9, "Banpresto"},
            { 0xDD, "ncs"},
            { 0xE0, "jaleco"},
            { 0xE3, "varie"},
            { 0xE8, "asmik"},
            { 0xEB, "atlus"},
            { 0xF0, "a wave"},
            { 0x08, "capcom"},
            { 0x0B, "coconuts"},
            { 0x18, "hudsonsoft"},
            { 0x1D, "clary"},
            { 0x24, "pcm complete"},
            { 0x29, "seta"},
            { 0x32, "bandai"},
            { 0x35, "hector"},
            { 0x3C, "*entertainment i"},
            { 0x42, "Atlus"},
            { 0x47, "spectrum holoby"},
            { 0x4D, "malibu"},
            { 0x51, "acclaim"},
            { 0x54, "gametek"},
            { 0x57, "matchbox"},
            { 0x5B, "romstar"},
            { 0x60, "titus"},
            { 0x69, "electronic arts"},
            { 0x70, "Infogrammes"},
            { 0x73, "sculptered soft"},
            { 0x79, "accolade"},
            { 0x7F, "kemco"},
            { 0x86, "tokuma shoten intermedia "},
            { 0x8E, "ape"},
            { 0x92, "video system"},
            { 0x96, "yonezawa/s'pal"},
            { 0x9A, "nihon bussan"},
            { 0x9D, "Banpresto"},
            { 0xA2, "Bandai"},
            { 0xA7, "takara"},
            { 0xAC, "Toei animation"},
            { 0xB0, "Acclaim"},
            { 0xB4, "Enix"},
            { 0xB9, "pony canyon"},
            { 0xBD, "Sony imagesoft"},
            { 0xC2, "Kemco"},
            { 0xC5, "data east"},
            { 0xC9, "ufl"},
            { 0xCC, "use"},
            { 0xCF, "angel"},
            { 0xD2, "quest"},
            { 0xD6, "naxat soft"},
            { 0xDA, "tomy"},
            { 0xDE, "human"},
            { 0xE1, "towachiki"},
            { 0xE5, "epoch"},
            { 0xE9, "natsume"},
            { 0xEC, "Epic/Sony records"},
            { 0xF3, "extreme entertainment"}
        };
    }
}
